Repository honestbank/terraform-confluent-kafka, pull requests merged in 2022-08, with the labels that each got.

#1 feat: create terraform confluent module
  .checkov.yaml
  .github/workflows/checkov.yml
  .github/workflows/shiftleft-terraform.yml
  .github/workflows/terraform.yml
  .github/workflows/terratest.yml
  .pre-commit-config.yaml
  .terraform-docs-examples.yml
  .terraform-docs-modules.yml
  Makefile
  README.md
  examples/create-env-cluster-topics/README.md
  examples/create-env-cluster-topics/inputs.tf
  examples/create-env-cluster-topics/main.tf
  examples/create-env-cluster-topics/outputs.tf
  examples/create-env-cluster-topics/providers.tf
  makefile
  modules/cluster-admin/README.md
  modules/cluster-admin/inputs.tf
  modules/cluster-admin/main.tf
  modules/cluster-admin/outputs.tf
  modules/cluster-admin/providers.tf
  modules/environment/README.md
  modules/environment/inputs.tf
  modules/environment/main.tf
  modules/environment/outputs.tf
  modules/environment/providers.tf
  modules/kafka-cluster/README.md
  modules/kafka-cluster/inputs.tf
  modules/kafka-cluster/main.tf
  modules/kafka-cluster/outputs.tf
  modules/kafka-cluster/providers.tf
  modules/kafka-topic/README.md
  modules/kafka-topic/inputs.tf
  modules/kafka-topic/main.tf
  modules/kafka-topic/outputs.tf
  modules/kafka-topic/providers.tf
  modules/service-account/README.md
  modules/service-account/input.tf
  modules/service-account/main.tf
  modules/service-account/outputs.tf
  modules/service-account/providers.tf
  test/create_env_cluster_topics_test.go
  test/go.mod
  test/go.sum
Labels: size/XXL

#3 feat(confluent): add randomized suffix to component module
  examples/create-env-cluster-topics/main.tf
  examples/create-env-cluster-topics/providers.tf
  modules/cluster-admin/main.tf
  modules/cluster-admin/outputs.tf
  modules/environment/main.tf
  modules/kafka-cluster/main.tf
  modules/service-account/main.tf
  test/create_env_cluster_topics_test.go
Labels: size/M

#4 refactor(confluent): remove random from component module
  modules/cluster-admin/main.tf
  modules/environment/main.tf
  modules/kafka-cluster/main.tf
  modules/service-account/main.tf
Labels: size/S
