Repository honestbank/terraform-confluent-kafka, pull requests merged in 2023-03, with the labels that each got.

#17 fix: avoid recreation of connector on status change
  modules/connector/main.tf
Labels: size/XS

#18 chore: update version of cycjimmy/semantic-release-action that is outdated and failing
  .github/workflows/repository-terratest.yml
Labels: size/XS

#19 feat: add permissions to read topics into the 'connector-service-acco…
  modules/connector-service-account/inputs.tf
  modules/connector-service-account/main.tf
Labels: size/M

#20 ci(release): Fix permissions on release workflow
  .github/semantic.yml
  .github/workflows/repository-terratest.yml
  .pre-commit-config.yaml
  modules/connector-service-account/README.md
  modules/kafka-cluster/README.md
Labels: size/S
